### ISSUE TITLE
Polymer requires node 6

### ISSUE THREAD

**Issue by uhoreg** [jefferyb/docker-polymer-cli#3]
When trying to run the latest image, I get an error:
```
Polymer CLI requires at least Node v6. You have v4.8.4.
See https://www.polymer-project.org/2.0/docs/tools/node-support for details.
```
Changing the Dockerfile to use node:6-slim and rebuilding works, although polymer serve seems to listen on port 8081 instead of 8080

**Comment by jefferyb** [comment]
@uhoreg Thanks for the info... I've updated the image and added an alpine version too...
Thanks again,
-Jeffery
